# Harmony Jekyll theme general configurations

# Base URL
baseurl:

# Site live URL
url: http://kuanghy.github.io

# Localhost
# url: http://127.0.0.1:4000

# Production URL for sitemap
production_url: http://kuanghy.github.io

# Harmony theme configuration. Please change accordingly.
harmony:
  name: 旷世的忧伤
  # Little description about your site
  description: Huoty's Blog
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   Harmony is a free responsive jekyll theme by Gayan Virajith
   and Maheshika Lakmali. Sourced on Github -
   https://github.com/gayanvirajith/harmony
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Huoty Kong
    email: sudohuoty@163.com
    url: http://konghy.cn

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: gayanvirajith
    twitter: gayanvirajith
    facebook: gayanvirajith
    gplus: +GayanVirajith
    dribble: gayan
    pinterest:
  social_zh:
    email: sudohuoty@163.com
    weibo: loveqing2013
    github: kuanghy
    qq:
    wechat:
    rss: /feed
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink: /:year/:month/:day/:title

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
